const BACKGROUND_COLOR_MAIN = `#F8F8F8`;
const LIGHT_BLUE = `#63d2ff`;
const DARK_BLUE = `#2081c3`;
const GREEN = `#1cfeba`;
const RED = `#FF0000`;
const PURPLE = `#3f37c9`;
const BLUE_PURPLE = `#3f37c9`;
const WHITE = `#FFFFFF`;
const BLACK = `#00000`;
const NAV_BAR_GREEN = `#47FFA7`;
const COMPLETED_GREEN = `#96FF71`;
const TEXT_COLOR = `#373737`;
const MODAL_GREEN = `#97FFCD`;
const EDIT_BUTTON_BLUE = `#5033FF`;
const CANCEL_BUTTON_BACKGROUND = `#E5E5E5`;
const DARK_GREEN = `#00AC5A`;

export { DARK_GREEN, BACKGROUND_COLOR_MAIN, LIGHT_BLUE, DARK_BLUE, GREEN, RED, PURPLE, BLUE_PURPLE, WHITE, BLACK, NAV_BAR_GREEN, COMPLETED_GREEN,TEXT_COLOR,MODAL_GREEN,EDIT_BUTTON_BLUE, CANCEL_BUTTON_BACKGROUND};